CONFIG_METRICS = "insights"
CONFIG_MODEL_TYPE_PATTERNS = "model_type_patterns"
CONFIG_FOLDER_TYPE_PATTERNS = "folder_type_patterns"
CONFIG_CONTRACT_PATTERNS = "contract_patterns"
CONFIG_DTYPES_PATTERNS = "dtypes_patterns"
CONFIG_SEVERITY = "severity"
