name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pypy38-cover:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up PyPy
        uses: actions/setup-python@v4
        with:
          python-version: "pypy-3.8"
          architecture: x64
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install tox tox-gh-actions
      
      - name: Test with tox
        run: tox 