name: build
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.11'
            toxpython: 'python3.11'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.11'
            toxpython: 'python3.11'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py39-pydantic28-cover (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pydantic28-cover'
            os: 'ubuntu-latest'
          - name: 'py39-pydantic28-cover (windows)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pydantic28-cover'
            os: 'windows-latest'
          - name: 'py39-pydantic28-cover (macos)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pydantic28-cover'
            os: 'macos-13'
          - name: 'py39-pydantic210-cover'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pydantic210-cover'
            os: 'ubuntu-latest'
          - name: 'py39-pydantic28-nocov'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pydantic28-nocov'
            os: 'ubuntu-latest'
          - name: 'py39-pydantic210-nocov'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-pydantic210-nocov'
            os: 'ubuntu-latest'
          - name: 'py310-pydantic28-cover'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pydantic28-cover'
            os: 'ubuntu-latest'
          - name: 'py310-pydantic210-cover'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pydantic210-cover'
            os: 'ubuntu-latest'
          - name: 'py310-pydantic28-nocov'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pydantic28-nocov'
            os: 'ubuntu-latest'
          - name: 'py310-pydantic210-nocov'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-pydantic210-nocov'
            os: 'ubuntu-latest'
          - name: 'py311-pydantic28-cover'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pydantic28-cover'
            os: 'ubuntu-latest'
          - name: 'py311-pydantic210-cover'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pydantic210-cover'
            os: 'ubuntu-latest'
          - name: 'py311-pydantic28-nocov'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pydantic28-nocov'
            os: 'ubuntu-latest'
          - name: 'py311-pydantic210-nocov'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311-pydantic210-nocov'
            os: 'ubuntu-latest'
          - name: 'py312-pydantic28-cover'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pydantic28-cover'
            os: 'ubuntu-latest'
          - name: 'py312-pydantic210-cover'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pydantic210-cover'
            os: 'ubuntu-latest'
          - name: 'py312-pydantic28-nocov'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pydantic28-nocov'
            os: 'ubuntu-latest'
          - name: 'py312-pydantic210-nocov'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312-pydantic210-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy39-pydantic28-cover'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pydantic28-cover'
            os: 'ubuntu-latest'
          - name: 'pypy39-pydantic210-cover'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pydantic210-cover'
            os: 'ubuntu-latest'
          - name: 'pypy39-pydantic28-nocov'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pydantic28-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy39-pydantic210-nocov'
            python: 'pypy-3.9'
            toxpython: 'pypy3.9'
            python_arch: 'x64'
            tox_env: 'pypy39-pydantic210-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy310-pydantic28-cover'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pydantic28-cover'
            os: 'ubuntu-latest'
          - name: 'pypy310-pydantic210-cover'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pydantic210-cover'
            os: 'ubuntu-latest'
          - name: 'pypy310-pydantic28-nocov'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pydantic28-nocov'
            os: 'ubuntu-latest'
          - name: 'pypy310-pydantic210-nocov'
            python: 'pypy-3.10'
            toxpython: 'pypy3.10'
            python_arch: 'x64'
            tox_env: 'pypy310-pydantic210-nocov'
            os: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: >
        tox -e ${{ matrix.tox_env }} -v
